@startuml
title 点餐流程图

start
: 扫码页;
note right: booking api
if(是否配置预点餐)then(yes)
: 扫码页(有预点餐入口);
else(no)
: 扫码页;
endif
fork
	:扫码;
	fork again
	:预点餐;
	
	:门店选择页面;
	note left: shopling api
	-> 选择门店;
	end fork

:点餐首页;
note right
index api

querytable api;

socket 连接
end note

if(桌位是否有订单)then(yes)
: 订单详情页;
end
else(no)
fork
	:菜品列表;
	fork again
	:购物车;
	end fork
-> 点餐(+-购物车);
:+-按钮;
note right
发送socket消息

接受socket同步
end note
:socket;
if(socket同步)then(fail)
:无反应;
stop
else(success)
:购物车;


->下单;
:核单页;
:支付页;
note right: payinfo api
->支付;
note right: pay post api
:订单详情页;
note right: orderdetail api


end


@enduml
