@startuml
扫码页 --> Server: 渲染，获取预点餐设置
note over 扫码页: booking api
扫码页 -> 选择门店页面: 预点餐选择门店
扫码页 -> 首页: 直接扫码


选择门店页面 --> Server: 获取地里位置信息，并获取门店列表
note over 选择门店页面: shoplist api
选择门店页面 --> Server: 获取城市列表
note over 选择门店页面: citylist api
选择门店页面 --> Server: 选择城市后，根据城市id获取门店列表
note over 选择门店页面: getshoplistByCid api 


选择门店页面 -> 首页:进入首页
首页->首页: 进入首页，各种逻辑判断
首页 --> Server: 首页加载时，拉取数据渲染
note over 首页: index api
首页 -->Server: 加入购物车时，未授权时,弹窗授权
note over 首页: login api
首页 -> 菜品列表购物车:包含               
首页 -> 购物车:包含               

box "首页" #LightBlue
	participant 菜品列表购物车
	participant 云购物车
end box
participant 购物车

group Loop

菜品列表购物车 --> 云购物车: send 新用户加入
云购物车 --> 菜品列表购物车: 全量菜品

菜品列表购物车 --> 云购物车: 加减菜，增量给云购物车
云购物车 --> 菜品列表购物车: 全量菜品和当前操作菜品

菜品列表购物车 --> 云购物车: 清空购物车
云购物车 --> 菜品列表购物车: 同步
end

首页 -> 核单页: 如果预点餐订单时

扫码页 -> 订单详情页:扫付(有订单时)
订单详情页 -> Server: 渲染，拉取订单详情
note over 订单详情页: getOrderInfo api
首页--> Server: 进入首页时，链接socket
note over 首页: socke api
首页--> Server: 获取地里位置信息，检测位置
note over 首页: compareDistance api 
首页-> 扫码页:超出范围

首页--> Server: 查询桌台是否有订单
note over 首页: queryTable api
首页 -> 订单详情页: 桌台有单时
首页 -> 订单列表:进入订单列表

订单列表 --> Server: 渲染，拉取订单列表
note over 订单列表: order api
订单列表 --> Server: 取消订单
note over 订单列表: cancelOrder api
订单列表 --> Server: 取消支付
note over 订单列表: unlockOrder api


购物车 -> 扫码页:预点餐
购物车 -> 核单页:提交购物车
扫码页 --> Server: 获取预点餐购物车数据
note over 扫码页: getBookingDetail api 

核单页 --> Server: 下单前，绑定手机号
note over 核单页: bindPhone api
核单页 --> Server: 下单
note over 核单页: placeOrder api

支付页--> Server: 渲染页面时，拉取支付信息
note over 支付页: pay api
支付页--> Server: 支付并查询结果
note over 支付页: postpay api
note over 支付页: payresult api


支付页 -> 订单详情页:支付完成/失败
核单页 -> 订单详情页: 后付/先付
订单详情页 -> 支付页: 未支付

订单列表 -> 订单详情页: 进入详情
订单详情页 -> 首页: 加菜

订单详情页 --> Server: 取消订单
note over 订单详情页: cancelBooking api
订单详情页 --> Server: 检测订单，是否有变更
note over 订单详情页: checkOrder api
订单详情页 --> Server: 取消支付，解锁
note over 订单详情页: unlockOrder api


支付页 --> Server: 切换卡，重新拉取支付信息
note over 支付页: pay api 
支付页 --> Server: 充值，及获取充值结果
note over 支付页: postcharge api 
note over 支付页: chargeresult api 
支付页 --> Server: 获取手机号
note over 支付页: bindPhonex api
支付页 --> Server: 取消支付
note over 支付页: unlockOrder api

box "Server"
participant Server
end box

@enduml